# Generated by Django 6.0.2 on 2026-03-16 00:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_adminprofile_studentprofile_teacherprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da turma"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "class_status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativa"), ("ARCHIVED", "Arquivada")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status da turma",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="accounts.teacherprofile",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(verbose_name="Matriculado em")),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativa"), ("REMOVED", "Removida")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status da matrícula",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.studentprofile",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="classes.classgroup",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(
                fields=["teacher_profile"], name="idx_classgroup_teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(fields=["class_status"], name="idx_classgroup_status"),
        ),
        migrations.AlterUniqueTogether(
            name="classgroup",
            unique_together={("teacher_profile", "name")},
        ),
        migrations.AddIndex(
            model_name="classenrollment",
            index=models.Index(
                fields=["student_profile"], name="idx_enrollment_student"
            ),
        ),
        migrations.AddIndex(
            model_name="classenrollment",
            index=models.Index(
                fields=["enrollment_status"], name="idx_enrollment_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classenrollment",
            unique_together={("class_group", "student_profile")},
        ),
    ]
