# Generated by Django 6.0.2 on 2026-03-16 11:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_adminprofile_studentprofile_teacherprofile_and_more"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExerciseProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Não iniciado"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status do progresso",
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de tentativas"
                    ),
                ),
                (
                    "first_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Primeira tentativa em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="curriculum.exercise",
                        verbose_name="Exercício",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to="accounts.studentprofile",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Exercício",
                "verbose_name_plural": "Progressos de Exercício",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["exercise"], name="idx_ex_progress_exercise"),
                    models.Index(
                        fields=["progress_status"], name="idx_ex_progress_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile", "exercise"),
                        name="uq_student_exercise_progress",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentLessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Não iniciado"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status do progresso",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="curriculum.lesson",
                        verbose_name="Aula",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="accounts.studentprofile",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Aula",
                "verbose_name_plural": "Progressos de Aula",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["lesson"], name="idx_les_progress_lesson"),
                    models.Index(
                        fields=["progress_status"], name="idx_les_progress_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile", "lesson"),
                        name="uq_student_lesson_progress",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentModuleProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Não iniciado"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status do progresso",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="curriculum.module",
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to="accounts.studentprofile",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Módulo",
                "verbose_name_plural": "Progressos de Módulo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["module"], name="idx_mod_progress_module"),
                    models.Index(
                        fields=["progress_status"], name="idx_mod_progress_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile", "module"),
                        name="uq_student_module_progress",
                    )
                ],
            },
        ),
    ]
