# Generated by Django 6.0.2 on 2026-03-21 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
