# Generated by Django 6.0.2 on 2026-03-16 00:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_adminprofile_studentprofile_teacherprofile_and_more"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_code", models.TextField(verbose_name="Código-fonte")),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando avaliação"),
                            ("RUNNING", "Em processamento"),
                            ("EVALUATED", "Avaliada"),
                            ("FAILED", "Falha no processamento"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status da avaliação",
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentual de acertos",
                    ),
                ),
                ("submitted_at", models.DateTimeField(verbose_name="Submetido em")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="curriculum.exercise",
                        verbose_name="Exercício",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="accounts.studentprofile",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissão",
                "verbose_name_plural": "Submissões",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "passed_tests_count",
                    models.PositiveIntegerField(verbose_name="Testes aprovados"),
                ),
                (
                    "failed_tests_count",
                    models.PositiveIntegerField(verbose_name="Testes reprovados"),
                ),
                (
                    "feedback_message",
                    models.TextField(verbose_name="Mensagem de feedback"),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Aprovada"),
                            ("FAILED", "Reprovada"),
                            ("ERROR", "Erro técnico"),
                        ],
                        max_length=20,
                        verbose_name="Resultado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="submissions.submission",
                        verbose_name="Submissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado da Submissão",
                "verbose_name_plural": "Resultados das Submissões",
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["exercise"], name="idx_submission_exercise"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student_profile"], name="idx_submission_student"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student_profile", "exercise", "submitted_at"],
                name="idx_submission_student_ex_date",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["evaluation_status"], name="idx_submission_eval_status"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionresult",
            index=models.Index(fields=["result_status"], name="idx_result_status"),
        ),
    ]
