# Generated by Django 6.0.2 on 2026-03-14 19:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("written_content", models.TextField(verbose_name="Conteúdo escrito")),
                (
                    "sequence_order",
                    models.PositiveIntegerField(verbose_name="Ordem na aula"),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status de publicação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["module", "sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("statement", models.TextField(verbose_name="Enunciado")),
                (
                    "support_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de apoio"
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveIntegerField(verbose_name="Ordem no exercício"),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status de publicação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="curriculum.lesson",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício",
                "verbose_name_plural": "Exercícios",
                "ordering": ["lesson", "sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "sequence_order",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Ordem na trilha"
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status de publicação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["sequence_order"],
                "indexes": [
                    models.Index(
                        fields=["publication_status"], name="idx_module_pub_status"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="curriculum.module",
                verbose_name="Módulo",
            ),
        ),
        migrations.CreateModel(
            name="VideoLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("video_url", models.URLField(verbose_name="URL do vídeo")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duração (segundos)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="curriculum.lesson",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Videoaula",
                "verbose_name_plural": "Videoaulas",
            },
        ),
        migrations.CreateModel(
            name="ExerciseTestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do teste"),
                ),
                (
                    "input_data",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dados de entrada"
                    ),
                ),
                ("expected_output", models.TextField(verbose_name="Saída esperada")),
                (
                    "sequence_order",
                    models.PositiveIntegerField(verbose_name="Ordem de execução"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="Oculto ao aluno"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="curriculum.exercise",
                        verbose_name="Exercício",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso de Teste",
                "verbose_name_plural": "Casos de Teste",
                "ordering": ["exercise", "sequence_order"],
                "indexes": [
                    models.Index(fields=["exercise"], name="idx_testcase_exercise")
                ],
                "unique_together": {("exercise", "sequence_order")},
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(fields=["lesson"], name="idx_exercise_lesson"),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["publication_status"], name="idx_exercise_pub_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={("lesson", "sequence_order")},
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["module"], name="idx_lesson_module"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["publication_status"], name="idx_lesson_pub_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("module", "sequence_order")},
        ),
        migrations.AddIndex(
            model_name="videolesson",
            index=models.Index(fields=["lesson"], name="idx_videolesson_lesson"),
        ),
    ]
